"""add data store tables

Revision ID: 4d9a91f48e78
Revises: 
Create Date: 2026-02-07 20:49:16.119119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9a91f48e78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_status',
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('last_collection', sa.String(length=64), nullable=False),
    sa.Column('last_fields_count', sa.Integer(), nullable=False),
    sa.Column('last_fields', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('region')
    )
    op.create_table('live_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('mibor', sa.Float(), nullable=False),
    sa.Column('repo', sa.Float(), nullable=False),
    sa.Column('cblo', sa.Float(), nullable=False),
    sa.Column('usdinr', sa.Float(), nullable=False),
    sa.Column('gsec', sa.Float(), nullable=False),
    sa.Column('call_avg', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_snap_date_hour', 'live_snapshots', ['date', 'hour'], unique=False)
    op.create_table('rate_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('fields_count', sa.Integer(), nullable=False),
    sa.Column('rates', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_snap_region_ts', 'rate_snapshots', ['region', 'timestamp'], unique=False)
    op.create_table('scraper_cache',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('training_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metadata_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_meta_type', 'training_metadata', ['metadata_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_meta_type', table_name='training_metadata')
    op.drop_table('training_metadata')
    op.drop_table('scraper_cache')
    op.drop_index('ix_rate_snap_region_ts', table_name='rate_snapshots')
    op.drop_table('rate_snapshots')
    op.drop_index('ix_live_snap_date_hour', table_name='live_snapshots')
    op.drop_table('live_snapshots')
    op.drop_table('collection_status')
    # ### end Alembic commands ###
